### ISSUE TITLE
Sublime text crash on Ubuntu after successful Update GEM

### ISSUE THREAD

**Issue by agawande** [vtphan/GEM#1]
Hi Dr. Phan,

On Ubuntu 16.04 and 18.04, my sublime text 3 (installed from their apt method with version: Sublime Text Build 3176) crashes with a segmentation fault after I click okay or cross on the dialog "GEM has been updated to version 0.91":

```
reloading plugin GEMStudent.GEMStudent
:0                                                                plugins loaded
reloading plugin GEMStudent.GEMStudent
Segmentation fault (core dumped)
```
The behavior is repeatable and happens every time.
If I remove [the dialog line](https://github.com/vtphan/GEM/blob/master/src/GEMStudent/GEMStudent.py#L502) line or change it to:
sublime.error_message("GEM has been updated to version %s." % version),
I do not get the crash.
I am not sure how to debug the crash further.

**Comment by vtphan** [comment]
Thanks for reporting the error.
When you get the error, can you open the console (“View / Console”) and let me know what the error message is?

Thanks.

Vinhthuy Phan
Associate Professor, Associate Chair
Department of Computer Science
[UofM logo]     The University of Memphis
375 Dunn Hall
Memphis, TN 38152<http://www.memphis.edu/emailsignatures/emailsignaturemac.php#>

901.678.<http://www.memphis.edu/emailsignatures/emailsignaturemac.php#>1535 | memphis.edu<http://www.memphis.edu/>/cs


On Oct 7, 2018, at 10:02 AM, Ashlesh Gawande <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dr. Phan,

On Ubuntu 16.04 and 18.04, my sublime text 3 (installed from their apt method with version: Sublime Text Build 3176) crashes with a segmentation fault after I click okay or cross on the dialog "GEM has been updated to version 0.91":

reloading plugin GEMStudent.GEMStudent
:0                                                                plugins loaded
reloading plugin GEMStudent.GEMStudent
Segmentation fault (core dumped)


The behavior is repeatable and happens every time.
If I remove the dialog line<https://github.com/vtphan/GEM/blob/master/src/GEMStudent/GEMStudent.py#L502> line or change it to:
sublime.error_message("GEM has been updated to version %s." % version),
I do not get the crash.
I am not sure how to debug the crash further.

**Comment by vtphan** [comment]
Can you replace it with this: 

			sublime.message_dialog("GEM has been updated to version {}.".format(version))


If you view the console (View / Console), it will tell exactly what the error is.

Thanks.

**Comment by agawande** [comment]
That did not fix it.

I bring up the console in sublime text, but when I click on okay in the dialog box, sublime text itself crashes - so I can't view the console anymore.

I ran sublime text like ``subl --debug`` to show the logs in the terminal and saw the Segmentation fault. Maybe this is a problem with sublime text itself.
